on:
  push:
    branches:
      - main
permissions:
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@main
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::468996723840:role/gh-action-deploy-quiz-app-backend

      # Build inside Docker containers
      - run: sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
      - env:
           GH_TOKEN: ${{ secrets.FRONTEND_REPO_TOKEN }}
        run: |
          AWS_OUTPUT=$(aws cloudformation describe-stacks \
            --stack-name quiz-app-backend \
            --query "Stacks[0].Outputs" \
            --output json | jq -c 'map({(.OutputKey): .OutputValue}) | add')
          
          echo $AWS_OUTPUT | jq -r '.WebEndpoint' | gh variable set PUBLIC_AWS_ENDPOINT_URL --repo derrealstefabi/quiz-app
          echo $AWS_OUTPUT | jq -r '.AwsRegion' | gh variable set PUBLIC_AWS_REGION --repo derrealstefabi/quiz-app
          echo $AWS_OUTPUT | jq -r '.CognitoUserPoolId' | gh variable set PUBLIC_COGNITO_USER_POOL_ID --repo derrealstefabi/quiz-app
          echo $AWS_OUTPUT | jq -r '.CognitoClientId' | gh variable set PUBLIC_COGNITO_USER_POOL_CLIENT_ID --repo derrealstefabi/quiz-app
          echo $AWS_OUTPUT | jq -r '.CognitoEndpoint' | gh variable set PUBLIC_COGNITO_DOMAIN --repo derrealstefabi/quiz-app
  
          gh workflow run astro.yml \
            --repo derrealstefabi/quiz-app \
            --ref main